# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-12 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False, verbose_name='账户ID')),
                ('account_name', models.CharField(default='', max_length=20, verbose_name='用户名')),
                ('account_layout', models.IntegerField(null=True, verbose_name='总花销')),
            ],
            options={
                'verbose_name': '账户',
                'verbose_name_plural': '账户',
            },
        ),
        migrations.CreateModel(
            name='build',
            fields=[
                ('build_id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('build_name', models.CharField(max_length=20, verbose_name='订单名')),
                ('build_blueprint', models.CharField(max_length=255, null=True, verbose_name='蓝图')),
                ('build_blueprint_price', models.IntegerField(verbose_name='设计费')),
                ('build_date', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
                ('build_wood', models.IntegerField(null=True, verbose_name='木材估量')),
                ('build_light', models.IntegerField(null=True, verbose_name='灯具估量')),
                ('build_floor', models.IntegerField(null=True, verbose_name='地板估量')),
                ('build_furniture', models.IntegerField(null=True, verbose_name='家具估量')),
                ('record_delete_status', models.CharField(choices=[('dele', '已删除'), ('no', '正常')], default='正常', max_length=4, verbose_name='删除')),
                ('build_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildAccount', to='myapp.account')),
            ],
            options={
                'verbose_name': '订单表',
                'verbose_name_plural': '订单表项',
            },
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='评论id')),
                ('comment_content', models.CharField(max_length=255, verbose_name='内容')),
                ('comment_time', models.DateTimeField(verbose_name='评论时间')),
                ('comment_build_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentBuildId', to='myapp.build')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='constractor',
            fields=[
                ('constractor_id', models.AutoField(primary_key=True, serialize=False, verbose_name='承包商ID')),
                ('constractor_name', models.CharField(default='', max_length=20, verbose_name='承包商名称')),
                ('constractor_price', models.IntegerField(null=True, verbose_name='承包商工费')),
                ('constractor_money', models.IntegerField(null=True, verbose_name='承包商花销')),
                ('constractor_delete', models.CharField(choices=[('dele', '已删除'), ('no', '正常')], default='正常', max_length=4, verbose_name='承包商删除位')),
            ],
            options={
                'verbose_name': '承包商',
                'verbose_name_plural': '承包商',
            },
        ),
        migrations.CreateModel(
            name='designer',
            fields=[
                ('designer_id', models.AutoField(primary_key=True, serialize=False, verbose_name='设计师id')),
                ('designer_name', models.CharField(max_length=20, verbose_name='设计师姓名')),
                ('designer_money', models.IntegerField(verbose_name='总花销')),
            ],
            options={
                'verbose_name': '设计师',
                'verbose_name_plural': '设计人员',
            },
        ),
        migrations.CreateModel(
            name='log',
            fields=[
                ('log_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='日志id')),
                ('log_tender', models.DateTimeField(verbose_name='招标节点')),
                ('log_construction', models.DateTimeField(verbose_name='施工时间节点')),
                ('log_accept', models.DateTimeField(verbose_name='验收时间节点')),
                ('log_build_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buildId', to='myapp.build')),
            ],
            options={
                'verbose_name': 'log',
                'verbose_name_plural': 'log表',
            },
        ),
        migrations.CreateModel(
            name='supply',
            fields=[
                ('supply_id', models.AutoField(primary_key=True, serialize=False, verbose_name='供应商ID')),
                ('supply_light', models.IntegerField(null=True, verbose_name='灯具单价')),
                ('supply_tel', models.IntegerField(null=True, verbose_name='联系方式')),
                ('supply_furniture', models.IntegerField(null=True, verbose_name='家具单价')),
                ('supply_wood', models.IntegerField(null=True, verbose_name='木材单价')),
                ('supply_floor', models.IntegerField(null=True, verbose_name='地板单价')),
                ('supply_name', models.CharField(default='', max_length=20, verbose_name='供应商名字')),
                ('supply_delete', models.IntegerField(choices=[('dele', '已删除'), ('no', '正常')], default='正常', max_length=4, verbose_name='删除状态位')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户主键')),
                ('user_pas', models.CharField(max_length=20, verbose_name='密码')),
                ('user_tel', models.CharField(max_length=11, verbose_name='电话')),
                ('user_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userAccountId', to='myapp.account')),
                ('user_contractor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userConstractorId', to='myapp.constractor')),
                ('user_designer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userDesignerId', to='myapp.designer')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户表',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentUserId', to='myapp.user'),
        ),
        migrations.AddField(
            model_name='build',
            name='build_contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buildContractorId', to='myapp.constractor'),
        ),
        migrations.AddField(
            model_name='build',
            name='build_designer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildDesignerId', to='myapp.designer'),
        ),
        migrations.AddField(
            model_name='build',
            name='build_supply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buildSupplyId', to='myapp.supply'),
        ),
    ]
