# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-12 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='supply_delete',
            field=models.IntegerField(choices=[('dele', '已删除'), ('no', '正常')], default='正常', verbose_name='删除状态位'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_account_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userAccountId', to='myapp.account'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_contractor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userConstractorId', to='myapp.constractor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_designer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userDesignerId', to='myapp.designer'),
        ),
    ]
