# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-13 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170913_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='bid',
            fields=[
                ('bid_id', models.AutoField(primary_key=True, serialize=False, verbose_name='竞标id')),
                ('bid_build_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidBuildId', to='myapp.build')),
                ('bid_contractor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidContractorId', to='myapp.constractor')),
            ],
            options={
                'verbose_name': '竞标',
                'verbose_name_plural': '竞标',
            },
        ),
    ]
