# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20170913_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='build_floor_price',
            field=models.IntegerField(null=True, verbose_name='地板实价'),
        ),
        migrations.AddField(
            model_name='build',
            name='build_furniture_price',
            field=models.IntegerField(null=True, verbose_name='家具实价'),
        ),
        migrations.AddField(
            model_name='build',
            name='build_light_price',
            field=models.IntegerField(null=True, verbose_name='灯具实价'),
        ),
        migrations.AddField(
            model_name='build',
            name='build_wood_price',
            field=models.IntegerField(null=True, verbose_name='木材实价'),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_accept',
            field=models.DateTimeField(auto_now_add=True, verbose_name='验收时间节点'),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_construction',
            field=models.DateTimeField(auto_now_add=True, verbose_name='施工时间节点'),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_tender',
            field=models.DateTimeField(auto_now_add=True, verbose_name='招标节点'),
        ),
    ]
