# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-13 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20170913_0232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='build',
            old_name='record_delete_status',
            new_name='build_delete_status',
        ),
    ]
