# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20170913_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='log_accept',
            field=models.DateField(default='1970-01-01', verbose_name='验收时间节点'),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_construction',
            field=models.DateField(default='1970-01-01', verbose_name='施工时间节点'),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_tender',
            field=models.DateField(default='1970-01-01', verbose_name='招标节点'),
        ),
    ]
